defaults: &defaults
  working_directory: /tmp/replay
  docker:
    - image: circleci/node:10.12-browsers
version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies for tests and builds
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: /tmp
          paths: replay/*
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Tests
          command: yarn test
      - run:
          name: Type checks
          command: yarn flow
      - run:
          name: ESLint
          command: yarn eslint src/replay
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Build
          command: yarn build:lib
      - persist_to_workspace:
          root: /tmp
          paths: replay/*
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Fetching private npm credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish
          command: echo Deactivated for now. --access public
      - run:
          name: Publishing documentation to GH pages.
          command: echo TODO.

workflows:
  version: 2
  all_tasks:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
